### PR TITLE
Improved Experience

### PR DESCRIPTION
**Pull request by FeistyKit**
I implemented parsing of any size commands, including using `exec` as a prefix. I also implemented it in a way that makes it easy to add asynchronous commands (ones that are called ending in "&"): all that has to be done is send them to another thread to be called. I improved install.py by requiring a correct answer instead of simply repeating it, and I implemented a way to preview the releases in the installer, as well as providing a way of installing a default configuration file. Finally, I improved error reporting and fixed crashes in the commands.

### CODE REVIEW

**Comment by Vaimer9** [comment]
I greatly appreciate the work that you have done in the past as well as in this PR. I can see how your code might be better, but reworking how the commands run is a little too much for me, I have no problem in adding the error handling commits that you have made, as well as in the install script but Im not so sure about the rework on command parsing.

**Comment by Vaimer9** [comment]
The current command parsing is somewhat temporary as right now I am working on vsh's scripting language so later on evaluating commands would just be feeding the interpreter one line at a time

**Review by Vaimer9 — APPROVED** [review]

**Comment by FeistyKit** [comment]
> The current command parsing is somewhat temporary as right now I am working on vsh's scripting language so later on evaluating commands would just be feeding the interpreter one line at a time

I think this will work, as the InternalCommand struct will handle all of that. I tried to make it as close as possible to the old Internalcommand system.

**Comment by Vaimer9** [comment]
Great to see that you understand, so would you like to submit a new PR with just the install script and the err handling changes, or I can commit on my own if you think it will he a hassle. I can act according to your convenience

**Pull request closed without merging**
